skip_clone: true

when:
  - branch: main
    event: [push]

steps:
  deploy:
    image: docker:28-cli
    commands: |
      apk add --no-cache curl

      curl -sL -o /tmp/Caddyfile \
        https://raw.githubusercontent.com/2eho/caddy-config/main/Caddyfile

      # 复制到 novelcat-edge 容器
      docker cp /tmp/Caddyfile novelcat-edge:/etc/caddy/Caddyfile

      # reload
      docker exec novelcat-edge caddy reload --config /etc/caddy/Caddyfile
